name: S01-L040-Runners

on:
  workflow_dispatch:
  push:
    paths:
#      - "api/**"
      - ".github/workflows/S01-L040-runners.yml"

jobs:
  build:
    name: build-dotnet-api
    runs-on: ubuntu-latest
    steps:
      - name: Pull the code (checkout)
        uses: actions/checkout@v4
      - name: Python version check
        run: python --version
      - name: List sdks
        run: dotnet --list-sdks
      - name: Build the app
        run: dotnet build weatherforecast-api-app.csproj
        working-directory: ./api
      - name: Testing the code
        run: dotnet test weatherforecast-api-app.csproj
        working-directory: ./api

