name: S01-L040-Runners

on:
  workflow_dispatch:
  push:
    paths:
#      - "api/**"
      - ".github/workflows/S01-L040-runners.yml"

jobs:
  build:
    name: python-app-setup
    runs-on: ubuntu-latest
    steps:
      - name: Pull the code (checkout)
        uses: actions/checkout@v4
      - name: Python version check
        run: python --version

